name: chart_sparkline
description: Beautiful sparkline charts for Flutter.
version: 1.0.1
homepage: https://github.com/biner88/chart_sparkline
publish_to: https://pub.dartlang.org
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
